
export const  proxy ='https://cors-anywhere.herokuapp.com'
export const key = '185642ca82ffb6918b7b29c4d3e68f46'
export const url ='http://www.food2fork.com/api'
export const apiMethods = {
    Search: 'search',
    GetRecipe : 'get'
}
export const mockData = {
    Recipe : '{"recipe":{"publisher":"The Pioneer Woman","f2f_url":"http://food2fork.com/view/47275","ingredients":["1 pound Pasta","2 Tablespoons Olive Oil","2 Tablespoons Butter","1 whole Medium Onion, Chopped Finely","2 cloves (to 3 Cloves) Garlic, Chopped","3/4 cups (to 1 Cup) Vodka","1 can (About 14 Oz.) Tomato Puree","1 cup Heavy Cream","1 pinch Red Pepper Flakes","1/4 teaspoon (to 1/2 Teaspoon) Salt","Freshly Ground Black Pepper, To Taste","1 cup Grated Parmesan Cheese"],"source_url":"http://thepioneerwoman.com/cooking/2008/12/friday-night-dinner-pasta-alla-vodka/","recipe_id":"47275","image_url":"http://static.food2fork.com/pastaallavodkaa870.jpg","social_rank":99.99999999999636,"publisher_url":"http://thepioneerwoman.com","title":"Pasta Alla Vodka"}}',
    Recipes : ' [{"publisher":"The Pioneer Woman","f2f_url":"http://food2fork.com/view/47025","title":"Pasta with Pesto Cream Sauce","source_url":"http://thepioneerwoman.com/cooking/2011/06/pasta-with-pesto-cream-sauce/","recipe_id":"47025","image_url":"http://static.food2fork.com/pestoa0e7.jpg","social_rank":100,"publisher_url":"http://thepioneerwoman.com"},{"publisher":"The Pioneer Woman","f2f_url":"http://food2fork.com/view/8f3e73","title":"The Best Lasagna Ever","source_url":"http://thepioneerwoman.com/cooking/2007/06/the_best_lasagn/","recipe_id":"8f3e73","image_url":"http://static.food2fork.com/387114468_aafd1be3404a2f.jpg","social_rank":100,"publisher_url":"http://thepioneerwoman.com"},{"publisher":"The Pioneer Woman","f2f_url":"http://food2fork.com/view/47032","title":"Shrimp Scampi","source_url":"http://thepioneerwoman.com/cooking/2011/04/16-minute-meal-shrimp-scampi/","recipe_id":"47032","image_url":"http://static.food2fork.com/scampibf5a.jpg","social_rank":100,"publisher_url":"http://thepioneerwoman.com"},{"publisher":"Two Peas and Their Pod","f2f_url":"http://food2fork.com/view/54426","title":"Creamy Avocado Pasta","source_url":"http://www.twopeasandtheirpod.com/creamy-avocado-pasta/","recipe_id":"54426","image_url":"http://static.food2fork.com/creamyavocadopasta607e.jpg","social_rank":99.99999999999989,"publisher_url":"http://www.twopeasandtheirpod.com"},{"publisher":"The Pioneer Woman","f2f_url":"http://food2fork.com/view/47275","title":"Pasta Alla Vodka","source_url":"http://thepioneerwoman.com/cooking/2008/12/friday-night-dinner-pasta-alla-vodka/","recipe_id":"47275","image_url":"http://static.food2fork.com/pastaallavodkaa870.jpg","social_rank":99.99999999999636,"publisher_url":"http://thepioneerwoman.com"},{"publisher":"The Pioneer Woman","f2f_url":"http://food2fork.com/view/46943","title":"Seafood Pasta","source_url":"http://thepioneerwoman.com/cooking/2012/03/seafood-pasta/","recipe_id":"46943","image_url":"http://static.food2fork.com/seafoodpasta5075.jpg","social_rank":99.99999999999329,"publisher_url":"http://thepioneerwoman.com"},{"publisher":"Smitten Kitchen","f2f_url":"http://food2fork.com/view/acaff5","title":"baked orzo with eggplant and mozzarella","source_url":"http://smittenkitchen.com/blog/2012/09/baked-orzo-with-eggplant-and-mozzarella/","recipe_id":"acaff5","image_url":"http://static.food2fork.com/7944232460_d833528bc615f4.jpg","social_rank":99.99999999997709,"publisher_url":"http://www.smittenkitchen.com"},{"publisher":"The Pioneer Woman","f2f_url":"http://food2fork.com/view/46882","title":"Bowtie Chicken Alfredo","source_url":"http://thepioneerwoman.com/cooking/2012/12/bowtie-chicken-alfredo/","recipe_id":"46882","image_url":"http://static.food2fork.com/chickenalfredoc9c5.jpg","social_rank":99.99999999993057}]'
    }
